# Generated by Django 5.1 on 2024-08-31 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=254)),
                ("author", models.CharField(default="Anonymous", max_length=100)),
                ("pages", models.IntegerField()),
                ("publication_date", models.DateField(help_text="Publication Date")),
                (
                    "classification",
                    models.IntegerField(
                        choices=[
                            (0, ""),
                            (1, "Romance"),
                            (2, "Adventure"),
                            (3, "Sci-fi"),
                        ],
                        default=0,
                    ),
                ),
            ],
        ),
    ]
