# Generated by Django 5.1 on 2024-09-20 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("biblioteca", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="title",
            field=models.CharField(max_length=254, unique=True),
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        help_text="Username of user what is booking", max_length=100
                    ),
                ),
                ("start_date", models.DateField(help_text="Start date of booking")),
                ("end_date", models.DateField(help_text="End date of booking")),
                (
                    "book",
                    models.ForeignKey(
                        help_text="Book Booked",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="biblioteca.book",
                    ),
                ),
            ],
        ),
    ]
