# Generated by Django 5.1 on 2024-09-21 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("biblioteca", "0002_alter_book_title_booking"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("full_name", models.CharField(max_length=254)),
                ("password", models.CharField(max_length=254)),
                (
                    "rol",
                    models.CharField(
                        choices=[("A", "Admin"), ("L", "Librarian"), ("S", "Student")],
                        default="E",
                        max_length=1,
                    ),
                ),
            ],
        ),
    ]
